name: Android CICD

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Move dir
      run: mv demo/build/outputs/apk/debug/demo-debug.apk AuroraLivePlayerDemo_$GITHUB_REF_NAME.apk
    - name: Deploy to Package
      uses: ncipollo/release-action@v1
      with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
